import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def _base_doc(buffer):
    return SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="TitleBig", fontSize=20, leading=24, spaceAfter=4, textColor=colors.HexColor("#1e3a5f")))
    styles.add(ParagraphStyle(name="Muted", fontSize=9, textColor=colors.HexColor("#6b7280")))
    styles.add(ParagraphStyle(name="Small", fontSize=9))
    return styles


def generate_invoice_pdf(bill: dict, tenant: dict, room: dict, owner_name: str = "RentFlow") -> bytes:
    buffer = io.BytesIO()
    doc = _base_doc(buffer)
    styles = _styles()
    elements = []

    elements.append(Paragraph(owner_name, styles["TitleBig"]))
    elements.append(Paragraph("Rent Invoice", styles["Muted"]))
    elements.append(Spacer(1, 10))

    header_data = [
        ["Invoice #", bill.get("bill_number", "-"), "Month", bill.get("month", "-")],
        ["Tenant", tenant.get("name", "-"), "Room", room.get("name", "-") if room else "-"],
        ["Due Date", bill.get("due_date", "-"), "Status", bill.get("status", "-").upper()],
    ]
    t = Table(header_data, colWidths=[70, 150, 70, 150])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6b7280")),
        ("TEXTCOLOR", (2, 0), (2, -1), colors.HexColor("#6b7280")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 16))

    rows = [["Description", "Amount"]]
    rows.append(["Room Rent", f"{bill.get('rent_amount', 0):.2f}"])
    for item in bill.get("line_items", []):
        rows.append([item.get("label", "Item"), f"{item.get('amount', 0):.2f}"])
    rows.append(["Total", f"{bill.get('total_amount', 0):.2f}"])
    rows.append(["Amount Paid", f"{bill.get('amount_paid', 0):.2f}"])
    rows.append(["Balance Due", f"{bill.get('balance', 0):.2f}"])

    items_table = Table(rows, colWidths=[350, 90])
    items_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.grey),
        ("LINEABOVE", (0, -3), (-1, -3), 0.5, colors.grey),
        ("FONTNAME", (0, -3), (-1, -1), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(items_table)
    elements.append(Spacer(1, 24))
    elements.append(Paragraph("Generated by RentFlow — thank you for your prompt payment.", styles["Muted"]))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()


def generate_receipt_pdf(payment: dict, bill: dict, tenant: dict, owner_name: str = "RentFlow") -> bytes:
    buffer = io.BytesIO()
    doc = _base_doc(buffer)
    styles = _styles()
    elements = []

    elements.append(Paragraph(owner_name, styles["TitleBig"]))
    elements.append(Paragraph("Payment Receipt", styles["Muted"]))
    elements.append(Spacer(1, 10))

    data = [
        ["Receipt #", payment.get("receipt_number", "-")],
        ["Date", payment.get("paid_on", "-")],
        ["Tenant", tenant.get("name", "-")],
        ["Bill Month", bill.get("month", "-") if bill else "-"],
        ["Payment Method", payment.get("method", "-").replace("_", " ").title()],
        ["Amount Paid", f"{payment.get('amount', 0):.2f}"],
    ]
    if payment.get("note"):
        data.append(["Note", payment.get("note")])

    t = Table(data, colWidths=[150, 300])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6b7280")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#e5e7eb")),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 24))
    elements.append(Paragraph("This is a computer-generated receipt.", styles["Muted"]))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
