const PDFDocument = require("pdfkit");

const NAVY = "#1e3a5f";
const MUTED = "#6b7280";
const GREY = "#808080";
const LIGHT_BORDER = "#e5e7eb";

const MARGIN = 20 * (72 / 25.4); // 20mm in points, matches reportlab margins

function newDoc() {
  return new PDFDocument({
    size: "A4",
    margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
  });
}

function collect(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}

function money(n) {
  return Number(n || 0).toFixed(2);
}

function header(doc, ownerName, subtitle) {
  doc.fillColor(NAVY).fontSize(20).text(ownerName, { continued: false });
  doc.fillColor(MUTED).fontSize(9).text(subtitle);
  doc.moveDown(1);
  doc.fillColor("black");
}

/** Two-column label/value row, mirrors the header table in the Python version. */
function labelValueRow(doc, left, x1, x2, x3, x4) {
  const y = doc.y;
  doc.fontSize(9).fillColor(MUTED).text(left[0], x1, y, { width: x2 - x1 });
  doc.fillColor("black").text(left[1], x2, y, { width: x3 - x2 });
  doc.fillColor(MUTED).text(left[2], x3, y, { width: x4 - x3 });
  doc.fillColor("black").text(left[3], x4, y);
  doc.moveDown(0.6);
}

async function generateInvoicePdf(bill, tenant, room, ownerName = "RentFlow") {
  const doc = newDoc();
  const pageWidth = doc.page.width - MARGIN * 2;
  const x0 = MARGIN;

  header(doc, ownerName, "Rent Invoice");

  const colW = pageWidth / 4;
  labelValueRow(
    doc,
    ["Invoice #", bill.bill_number || "-", "Month", bill.month || "-"],
    x0,
    x0 + colW,
    x0 + colW * 2,
    x0 + colW * 3
  );
  labelValueRow(
    doc,
    [
      "Tenant",
      (tenant && tenant.name) || "-",
      "Room",
      room ? room.name || "-" : "-",
    ],
    x0,
    x0 + colW,
    x0 + colW * 2,
    x0 + colW * 3
  );
  labelValueRow(
    doc,
    [
      "Due Date",
      bill.due_date || "-",
      "Status",
      (bill.status || "-").toUpperCase(),
    ],
    x0,
    x0 + colW,
    x0 + colW * 2,
    x0 + colW * 3
  );

  doc.moveDown(1);

  // Line items table
  const rows = [["Description", "Amount"]];
  rows.push(["Room Rent", money(bill.rent_amount)]);
  for (const item of bill.line_items || []) {
    rows.push([item.label || "Item", money(item.amount)]);
  }
  const totalRowIndex = rows.length; // index of "Total" row within `rows`
  rows.push(["Total", money(bill.total_amount)]);
  rows.push(["Amount Paid", money(bill.amount_paid)]);
  rows.push(["Balance Due", money(bill.balance)]);

  const descColW = pageWidth * 0.8;
  const amtColW = pageWidth * 0.2;
  let y = doc.y;

  // Header row with navy background
  doc.rect(x0, y, pageWidth, 20).fill(NAVY);
  doc
    .fillColor("white")
    .fontSize(10)
    .text("Description", x0 + 6, y + 6, { width: descColW - 6 });
  doc.text("Amount", x0 + descColW, y + 6, {
    width: amtColW - 6,
    align: "right",
  });
  y += 20;
  doc.fillColor("black");

  rows.slice(1).forEach((row, i) => {
    const isBoldRow = i + 1 >= totalRowIndex; // Total / Amount Paid / Balance Due
    doc.fontSize(10).font(isBoldRow ? "Helvetica-Bold" : "Helvetica");
    doc.text(row[0], x0 + 6, y + 6, { width: descColW - 6 });
    doc.text(row[1], x0 + descColW, y + 6, {
      width: amtColW - 6,
      align: "right",
    });
    if (i + 1 === totalRowIndex) {
      doc
        .strokeColor(GREY)
        .lineWidth(0.5)
        .moveTo(x0, y)
        .lineTo(x0 + pageWidth, y)
        .stroke();
    }
    y += 22;
  });
  doc.font("Helvetica");

  doc.y = y + 20;
  doc
    .fillColor(MUTED)
    .fontSize(9)
    .text("Generated by RentFlow — thank you for your prompt payment.", x0, doc.y);

  return collect(doc);
}

async function generateReceiptPdf(payment, bill, tenant, ownerName = "RentFlow") {
  const doc = newDoc();
  const pageWidth = doc.page.width - MARGIN * 2;
  const x0 = MARGIN;

  header(doc, ownerName, "Payment Receipt");

  const rows = [
    ["Receipt #", payment.receipt_number || "-"],
    ["Date", payment.paid_on || "-"],
    ["Tenant", (tenant && tenant.name) || "-"],
    ["Bill Month", bill ? bill.month || "-" : "-"],
    [
      "Payment Method",
      (payment.method || "-")
        .replace(/_/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase()),
    ],
    ["Amount Paid", money(payment.amount)],
  ];
  if (payment.note) {
    rows.push(["Note", payment.note]);
  }

  const labelColW = pageWidth * 0.33;
  let y = doc.y;
  for (const [label, value] of rows) {
    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .fillColor(MUTED)
      .text(label, x0, y, { width: labelColW });
    doc
      .font("Helvetica")
      .fillColor("black")
      .text(String(value), x0 + labelColW, y, { width: pageWidth - labelColW });
    y = doc.y + 4;
    doc
      .strokeColor(LIGHT_BORDER)
      .lineWidth(0.25)
      .moveTo(x0, y)
      .lineTo(x0 + pageWidth, y)
      .stroke();
    y += 6;
    doc.y = y;
  }

  doc.moveDown(1.5);
  doc.fillColor(MUTED).fontSize(9).text("This is a computer-generated receipt.", x0, doc.y);

  return collect(doc);
}

module.exports = { generateInvoicePdf, generateReceiptPdf };
